#!/bin/bash

TEXTEDIT="st -e nvim"
declare -a options=(
"AutoStart Script - /opt/xelph-dwm-git/scripts/autostart.sh"
"DWM scripts - /opt/xelph-dwm-git/scripts/"
"Config selector - /opt/xelph-dwm-git/scripts/configselector"
"NeoVim Config - $HOME/.config/nvim/init.vim"
"NeoVim Snippets - $HOME/.config/nvim/UltiSnips"
"Picom config - /opt/xelph-dwm-git/picom.conf"
"SXHKD keybinds - /opt/xelph-dwm-git/sxhkdrc"
"Xinitrc - $HOME/.xinitrc"
"Zsh aliases - $HOME/.zshrc-personal"
"Zshrc - $HOME/.zshrc"
)

choice=$(printf '%s\n' "${options[@]}"| dmenu -i -h 30 -p 'Edit config:')
if [[ "$choice" == "quit" ]]; then
	echo "Program terminated." && exit 1
elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	$TEXTEDIT $cfg
else 
	echo "Program terminated." && exit 1
fi
